### ISSUE TITLE
failed to cleanup volume on terminating pod

### ISSUE THREAD

**Issue by satoru-takeuchi** [topolvm/topolvm#227] opened 2020-12-03 00:56 UTC
**Describe the bug**

When terminating a pod with a volume created by TopoLVM, the volume is not cleaned up properly.

Probbably this problem happens because of using Kubernetes v1.19. Although TopoLVM doesn't support k8s v1.19 yet, it'll be done with the following issue.
https://github.com/topolvm/topolvm/issues/218

So let's investigate this problem with #218 .

slack discussion:
https://topolvm.slack.com/archives/CSXMYS3L2/p1606896433053000

Here is the detail (c-p from slack).

The kubelet log of terminating pod.
```
I1202 16:04:14.786783  476958 kubelet_pods.go:939] Pod "topolvm-test-2-es-default-2_uat-es(47251506-0d40-41ac-a60f-4c6a0e1596c4)" is terminated, but some volumes have not been cleaned up
```

topolvm-node received delete request from kubelet properly.

topolvm-node's log.
```
{"level":"info","ts":1606897350.6796362,"logger":"driver.node","msg":"NodeUnpublishVolume called","volume_id":"d87cc6a0-43f1-4970-86ba-8aa2aa8f010e","target_path":"/var/lib/k8s/kubelet/pods/4331c1d5-13e0-4ce1-8071-ff7fd8a51e4e/volumes/kubernetes.io~csi/pvc-4db743eb-53d8-4ab3-93ad-839e269732cc/mount"}
{"level":"info","ts":1606897385.0484025,"logger":"driver.identity","msg":"Probe","req":""}
{"level":"info","ts":1606897398.4616272,"logger":"driver.node","msg":"NodeGetVolumeStats is called","volume_id":"d87cc6a0-43f1-4970-86ba-8aa2aa8f010e","volume_path":"/var/lib/k8s/kubelet/pods/4331c1d5-13e0-4ce1-8071-ff7fd8a51e4e/volumes/kubernetes.io~csi/pvc-4db743eb-53d8-4ab3-93ad-839e269732cc/mount"}
```

However, the termination of PVC, that is corresponding to the volume, was blocked because there is a finalizer "kubernetes.io/pvc-protection".

```
Name:          elasticsearch-data-topolvm-test-es-default-1
Namespace:     uat-es
StorageClass:  topolvm-provisioner
Status:        Terminating (lasts 50m)
Volume:        pvc-4db743eb-53d8-4ab3-93ad-839e269732cc
Labels:        common.k8s.elastic.co/type=elasticsearch
               elasticsearch.k8s.elastic.co/cluster-name=topolvm-test
               elasticsearch.k8s.elastic.co/statefulset-name=topolvm-test-es-default
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: topolvm.cybozu.com
               volume.kubernetes.io/selected-node: svr6781hp360
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      2Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    topolvm-test-es-default-1
Events:        <none>
```

It means that there is a problem in terminating pod.

In addition, there is a error in lvmd, that is issued by kubelet.

```
I1202 16:10:04.786722  476958 kubelet.go:1993] SyncLoop (housekeeping)
I1202 16:10:04.786922  476958 kubelet_pods.go:939] Pod "topolvm-test-es-default-1_uat-es(4331c1d5-13e0-4ce1-8071-ff7fd8a51e4e)" is terminated, but some volumes have not been cleaned up
I1202 16:10:04.787046  476958 kubelet_pods.go:939] Pod "topolvm-test-2-es-default-2_uat-es(47251506-0d40-41ac-a60f-4c6a0e1596c4)" is terminated, but some volumes have not been cleaned up
E1202 16:10:04.802338  476958 kubelet_volumes.go:154] orphaned pod "ab8d3ba5-e202-48f1-bf07-b4c2a48c99f3" found, but volume paths are still present on disk : There were a total of 1 errors similar to this. Turn up verbosity to see them.
I1202 16:10:04.802357  476958 kubelet_pods.go:1720] Orphaned pod "4331c1d5-13e0-4ce1-8071-ff7fd8a51e4e" found, but volumes not yet removed.  Reducing cpu to minimum
I1202 16:10:04.802486  476958 kubelet_pods.go:1720] Orphaned pod "47251506-0d40-41ac-a60f-4c6a0e1596c4" found, but volumes not yet removed.  Reducing cpu to minimum
```

**Environments**
- Version: v0.6.0
- Kubernetes version: v1.19

**To Reproduce**

Not sure.

**Expected behavior**

Suceeded to remove Pod, PVC, PV, and LV properly.

**Additional context**

After restarting kubelet, all pod, pvc, and LV were deleted as expected.

**Comment by binoue** [comment] 2020-12-04 08:31
This was caused by a misconfiguration of mountPath and hostPath and not a TopoLVM bug.
Therefore, we would like to close this issue.

**Closed** 2020-12-04 08:38 UTC
Labels: bug
