### ISSUE TITLE
topolvm-node does not unmount btrfs volumes after running `parted -l`

### ISSUE THREAD

**Issue by seleznev** [topolvm/topolvm#877] opened 2024-04-05 16:05 UTC
**Describe the bug**

Looks like `parted -l` triggers udev rules that rename topolvm devices (`/dev/topolvm/c168dad9-978b-40e4-a45b-b77e141bff7a` -> `/dev/mapper/topolvm-c168dad9--978b--40e4--a45b--b77e141bff7a`). This is not an issue on the host system, but inside topolvm-node container there are no symlinks under `/dev/mapper/`, so the topolvm-node thinks the device is not mounted.

**Environments**

- Version: 0.27.0 (installed via Helm chart).
- OS: Ubuntu 22.04 (with 5.15 kernel).
- Kubernetes version: 1.28.8.

**To Reproduce**

1. Create a StorageClass with `fsType: btrfs`.
2. Create a Pod with generic ephemeral volume. Something like this:
   ```yaml
    apiVersion: v1
    kind: Pod
    metadata:
      name: test-pod
    spec:
      containers:
      - command:
        - sleep
        - infinity
        image: ubuntu:22.04
        name: test-container
        volumeMounts:
        - mountPath: /mnt/ephemeral-pv
          name: ephemeral-pv
      volumes:
      - ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
              storageClassName: topolvm-btrfs
              volumeMode: Filesystem
        name: ephemeral-pv
    ```
3. Wait until the Pod will be scheduled and ready.
4. Check `/proc/mounts` on the node:
    ```
    # cat /proc/mounts | grep pvc-
    /dev/topolvm/c168dad9-978b-40e4-a45b-b77e141bff7a /var/lib/kubelet/pods/a50597ec-22df-4c28-9f1b-6e5f7660499d/volumes/kubernetes.io~csi/pvc-40dfde50-d302-47d3-ba97-bebc4d003857/mount btrfs rw,relatime,space_cache=v2,subvolid=5,subvol=/ 0 0
    ```
5. Call `parted -l` on the node.
    ```
    # parted -l >/dev/null 2>&1
    ```
5. Check `/proc/mounts` on the node again (note that the device path changed from `/dev/topolvm/` to `/dev/mapper/`):
    ```
    # cat /proc/mounts | grep pvc-
    /dev/mapper/topolvm-c168dad9--978b--40e4--a45b--b77e141bff7a /var/lib/kubelet/pods/a50597ec-22df-4c28-9f1b-6e5f7660499d/volumes/kubernetes.io~csi/pvc-40dfde50-d302-47d3-ba97-bebc4d003857/mount btrfs rw,relatime,space_cache=v2,subvolid=5,subvol=/ 0 0
    ```
6. Delete the Pod.
7. Verify the Pod stuck in Terminating state.
8. Check topolvm-node logs on the node. You will see something like this:
    ```
    {"level":"info","ts":"2024-04-05T14:33:23Z","logger":"driver.node","msg":"NodeUnpublishVolume called","volume_id":"c168dad9-978b-40e4-a45b-b77e141bff7a","target_path":"/var/lib/kubelet/pods/a50597ec-22df-4c28-9f1b-6e5f7660499d/volumes/kubernetes.io~csi/pvc-40dfde50-d302-47d3-ba97-bebc4d003857/mount"}
    {"level":"error","ts":"2024-04-05T14:33:23Z","msg":"error on grpc call","method":"/csi.v1.Node/NodeUnpublishVolume","error":"rpc error: code = Internal desc = remove dir failed for /var/lib/kubelet/pods/a50597ec-22df-4c28-9f1b-6e5f7660499d/volumes/kubernetes.io~csi/pvc-40dfde50-d302-47d3-ba97-bebc4d003857/mount: error=unlinkat /var/lib/kubelet/pods/a50597ec-22df-4c28-9f1b-6e5f7660499d/volumes/kubernetes.io~csi/pvc-40dfde50-d302-47d3-ba97-bebc4d003857/mount: device or resource busy","stacktrace":"github.com/topolvm/topolvm/cmd/topolvm-node/app.ErrorLoggingInterceptor\n\t/workdir/cmd/topolvm-node/app/run.go:186\ngithub.com/container-storage-interface/spec/lib/go/csi._Node_NodeUnpublishVolume_Handler\n\t/go/pkg/mod/github.com/container-storage-interface/spec@v1.6.0/lib/go/csi/csi.pb.go:6168\ngoogle.golang.org/grpc.(*Server).processUnaryRPC\n\t/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:1374\ngoogle.golang.org/grpc.(*Server).handleStream\n\t/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:1751\ngoogle.golang.org/grpc.(*Server).serveStreams.func1.1\n\t/go/pkg/mod/google.golang.org/grpc@v1.58.3/server.go:986"}
    ```

**Expected behavior**

Pod should not stuck in Terminating state.

**Additional context**

To recover you can do something from the following list:

1. Create symlinks in `/dev/mapper/` and `/dev/topolvm/` inside topolvm-node container (same as on the host).
2. Manually unmount PV on the node (path can be found in topolvm-node's logs).
3. Reboot the node.

I can't reproduce it with ext4. Only with btrfs.

**Comment by cupnes** [comment] 2024-04-08 10:02
@seleznev 
I was able to reproduce the same error situation.

> but inside topolvm-node container there are no symlinks under `/dev/mapper/`

In my environment, there was a symlink.

```
$ kubectl get pv pvc-61981daf-b914-4115-a1c5-78b425f929a4 -oyaml
...
    volumeHandle: 45c537b6-00a6-466e-bff3-f6a8a1113305
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.topolvm.io/node
          operator: In
          values:
          - topolvm-e2e-worker2
...
$ docker container exec -it topolvm-e2e-worker2 bash
root@topolvm-e2e-worker2:/# ls -l /dev/mapper/ | grep '45c537b6--00a6--466e--bff3--f6a8a1113305'
lrwxrwxrwx 1 root root       8 Apr  8 09:42 node2--thick1-45c537b6--00a6--466e--bff3--f6a8a1113305 -> ../dm-10
```

Just to be sure, may I confirm if there are no symlinks in your environment?
(Or am I recreating a different situation from yours?)

**Comment by seleznev** [comment] 2024-04-08 11:15
@cupnes,

> Just to be sure, may I confirm if there are no symlinks in your environment?

* On the host system:
  ```
  root@worker1:~# ls -l /dev/topolvm/
  total 0
  lrwxrwxrwx 1 root root 7 апр  8 11:02 5d028020-146a-49fe-88f4-f574070b6738 -> ../dm-2
  lrwxrwxrwx 1 root root 7 апр  8 11:02 65760171-10b7-405e-9351-b68a7458e7a0 -> ../dm-1
  lrwxrwxrwx 1 root root 7 апр  8 11:02 root -> ../dm-0
  ```
  ```
  root@worker1:~# ls -l /dev/mapper/
  total 0
  crw------- 1 root root 10, 236 апр  4 00:19 control
  lrwxrwxrwx 1 root root       7 апр  8 11:02 topolvm-5d028020--146a--49fe--88f4--f574070b6738 -> ../dm-2
  lrwxrwxrwx 1 root root       7 апр  8 11:02 topolvm-65760171--10b7--405e--9351--b68a7458e7a0 -> ../dm-1
  lrwxrwxrwx 1 root root       7 апр  8 11:02 topolvm-root -> ../dm-0
  ```
* Inside `topolvm-node` container: 
  ```
  root@topolvm-node-h849s:/# ls -l /dev/topolvm/
  total 0
  brw------- 1 root root 253, 2 Apr  8 04:07 5d028020-146a-49fe-88f4-f574070b6738
  brw------- 1 root root 253, 1 Apr  3 17:22 65760171-10b7-405e-9351-b68a7458e7a0
  ```
  ```
  root@topolvm-node-h849s:/# ls -l /dev/mapper/
  total 0
  crw------- 1 root root 10, 236 Apr  3 17:21 control
  ```

> (Or am I recreating a different situation from yours?)

Maybe in e2e environment you mount `/dev` from the host system? It should solve the problem, but there are [no mount for `/dev` by default in the Helm chart](https://github.com/topolvm/topolvm/blob/main/charts/topolvm/templates/node/daemonset.yaml#L103-L122).

Can you also check `/dev/topolvm/`? It should not contains symlinks inside `topolvm-node` container (but they will be on the host system).

---

Please note that topolvm-node [creates device files in `/dev/topolvm/` now](https://github.com/topolvm/topolvm/blob/567532964002c8c9f8f54e1824010269f71e0413/internal/driver/node.go#L264). It should not be necessary if you have `/dev/mapper` or `/dev/topolvm` from the host.

As a result, if I delete `topolvm-node-h849s` now, `/dev/topolvm/` will be empty in the replacement Pod (because PVs already created and mounted).

**Comment by cupnes** [comment] 2024-04-09 08:33
@seleznev 
Thank you for your response. Before answering your question, please allow me to confirm the following.

> - On the host system:

What does the host system refer to? Is that the system on which the topolvm-node is running? For example, is the docker container `topolvm-e2e-worker2` the host system when topolvm-node exists as follows?

```
$ kubectl get pod -n topolvm-system -owide topolvm-node-z2k9w
NAME                 READY   STATUS    RESTARTS   AGE   IP           NODE                  NOMINATED NODE   READINESS GATES
topolvm-node-z2k9w   3/3     Running   0          21h   10.244.1.2   topolvm-e2e-worker2   <none>           <none>
```

**Comment by seleznev** [comment] 2024-04-09 09:29
@cupnes,

> Is that the system on which the topolvm-node is running?

Yes.

> For example, is the docker container topolvm-e2e-worker2 the host system when topolvm-node exists as follows?

Yes, it is. But not sure that the issue can be reproduced in this setup easialy. For example, if you don't have udev, nobody will rename devices. But you should still have empty `/dev/mapper/` inside `topolvm-node-z2k9w` (but it is not a problem by itself).

In my environment, "the host system" is a bare metal k8s node. kubelet+containerd running as systemd units (so, no additional docker layer in my case).

**Comment by cupnes** [comment] 2024-04-10 08:18
@seleznev 
Thank you for your reply. The same situation was reproduced. I could confirm that the device path is changed from `/dev/topolvm/` to `/dev/mapper/` when running `parted -l`, even in an environment set up with e2e. In this environment, `/dev/topolvm/` and `/dev/mapper/` were as follows.

- On the host system (Inside `topolvm-e2e-worker2` container):
  ```
  root@topolvm-e2e-worker2:/# ls -l /dev/topolvm/
  ls: cannot access '/dev/topolvm/': No such file or directory
  root@topolvm-e2e-worker2:/# ls -l /dev/mapper/
  total 0
  crw------- 1 root root 10, 236 Feb 15 01:37 control
  lrwxrwxrwx 1 root root       7 Apr  8 09:16 node1--thin1-pool0 -> ../dm-3
  lrwxrwxrwx 1 root root       7 Apr  8 09:16 node1--thin1-pool0_tdata -> ../dm-2
  lrwxrwxrwx 1 root root       7 Apr  8 09:16 node1--thin1-pool0_tmeta -> ../dm-1
  lrwxrwxrwx 1 root root       8 Apr  8 09:42 node2--thick1-45c537b6--00a6--466e--bff3--f6a8a1113305 -> ../dm-10
  lrwxrwxrwx 1 root root       7 Apr  8 09:16 node2--thin1-pool0 -> ../dm-6
  lrwxrwxrwx 1 root root       7 Apr  8 09:16 node2--thin1-pool0_tdata -> ../dm-5
  lrwxrwxrwx 1 root root       7 Apr  8 09:16 node2--thin1-pool0_tmeta -> ../dm-4
  lrwxrwxrwx 1 root root       7 Apr  8 09:16 node3--thin1-pool0 -> ../dm-9
  lrwxrwxrwx 1 root root       7 Apr  8 09:16 node3--thin1-pool0_tdata -> ../dm-8
  lrwxrwxrwx 1 root root       7 Apr  8 09:16 node3--thin1-pool0_tmeta -> ../dm-7
  lrwxrwxrwx 1 root root       7 Apr  8 09:42 ubuntu--vg-ubuntu--lv -> ../dm-0
  root@topolvm-e2e-worker2:/#
  ```
- Inside `topolvm-node` container:
  ```
  root@topolvm-node-z2k9w:/# ls -l /dev/topolvm/
  total 0
  brw------- 1 root root 253, 10 Apr  8 09:19 45c537b6-00a6-466e-bff3-f6a8a1113305
  root@topolvm-node-z2k9w:/# ls -l /dev/mapper/
  total 0
  crw------- 1 root root 10, 236 Apr  8 09:18 control
  root@topolvm-node-z2k9w:/#
  ```

The results on the host system differ from yours because, as you write, the host system is different from yours, and this is not so important. It is the results within `topolvm-node` that are important. It was confirmed that the file for the device exists in `/dev/topolvm/` but does not exist in `/dev/mapper/`. And I also confirmed that pod deletion stops in the Terminating state.

I think this issue should be fixed. Could you make PR for this issue? If you could do that I will review it.

And as a fixed policy, I think the following is better. At least, it is not better to create a symlink in `/dev/mapper/`. I think this directory is managed by the Linux DM.

> 2. Manually unmount PV on the node (path can be found in topolvm-node's logs).

**Comment by jakobmoellerdev** [comment] 2024-04-10 10:08
@cupnes I have a few questions after looking over this issue:

1. Why do we need to create a [device directory](https://github.com/topolvm/topolvm/blob/a967c95da14f80955332a00ebb258e319c6c39ac/internal/driver/node.go#L209) for managing topolvm device symlinks? I believe that lv creation should automatically create the device via device mapper, and that should be symlinkable since lvm2 calls device mapper (and triggers udev rules) where required.
2. Why do we not disable udev in the lvm configuration of lvm2? in the lvm2.conf:
  ```
	# Configuration option activation/udev_rules.
	# Use udev rules to manage LV device nodes and symlinks.
	# When disabled, LVM will manage the device nodes and symlinks for
	# active LVs itself. Manual intervention may be required if this
	# setting is changed while LVs are active.
	# This configuration option has an automatic default value.
	# udev_rules = 1
  ```
  I believe this causes side effects because we do not use device mapper (as you said above) and it conflicts with the topolvm device handling. I believe we could either switch to device creation via dmsetup on the host, or deactivate udev

**Comment by seleznev** [comment] 2024-04-10 10:21
@cupnes 
> Could you make PR for this issue? If you could do that I will review it.

I'm not sure that is a good idea. I'm not familiar with tests in this project, for example. Review can be painful. 

And more important, I have no idea how to properly fix that. :slightly_smiling_face:

**Comment by jakobmoellerdev** [comment] 2024-04-10 10:58
No worries, once there is clarity on what needs to be done I can submit a PR @seleznev . Just want to make sure that the TopoLVM device setup is handled correctly.

**Comment by cupnes** [comment] 2024-04-12 08:17
@jakobmoellerdev 
> I have a few questions after looking over this issue:

First of all, for 3. topolvm uses the lvm command to scan the lv device to get the major and minor numbers of the block special file and then uses mknod to create the block special file. The major and minor numbers are used, so even if /dev is mounted, the file must be scanned from there. The decision is that it is simpler to create it with mknod than to do that.
And for 1., as mentioned above, simply use the directory /dev/topolvm as the destination to mknod to.
And for 2., we don't want to do it because it might have an impact on other systems than topolvm.

@jakobmoellerdev @seleznev 
> I'm not sure that is a good idea. I'm not familiar with tests in this project, for example. Review can be painful.

> No worries, once there is clarity on what needs to be done I can submit a PR @seleznev . Just want to make sure that the TopoLVM device setup is handled correctly.

Thank you for considering it. However, we are still discussing this issue within our team. Please do not create a PR yet.

**Comment by jakobmoellerdev** [comment] 2024-04-12 09:17
> First of all, for 3. topolvm uses the lvm command to scan the lv device to get the major and minor numbers of the block special file and then uses mknod to create the block special file. The major and minor numbers are used, so even if /dev is mounted, the file must be scanned from there. 

Sorry for my naivety here, I may not have the experience you guys have here. Please correct me whenever I make a wrong assumption.

My view is: If you use major and minor, you are effectively creating the device yourself within the containers /dev that will be directed through the container runtime onto the host so that is not a problem. 

However, the device you create will not trigger any udev rules, even though udev may exist on the host system. Meaning that any device created in /dev/topolvm will not be visible to the host systems udev rules. At the same time, because you use lvm on the host system the device mapper still knows about the lvm volumes and will trigger udev rules.

Thats why using dmsetup or lvm would fix this, because you would do the device creation on the host and the tools like dmsetup or lvm would trigger udev automatically afaik.

**Comment by cupnes** [comment] 2024-04-15 09:10
@jakobmoellerdev 
Thank you for your comments. I discussed this with the team. We think the behavior of udev with `parted -l` doesn't go well with topolvm. We want to not change the lines about topolvm in `/proc/mounts`. A possible modification is that to support the host `/dev/mapper` to be mounted on topolvm-node. But it seems to take a lot of time and effort.
We are considering adding a constraint to docs/limitations.md that says "Do not change lines about topolvm in `/proc/mounts`". We will also write about this issue there. What do you think?

**Comment by jakobmoellerdev** [comment] 2024-04-15 10:32
I wonder why parted -l is changing the /proc/mounts here tbh. Do we have some info on that? Apart from that I agree that its important to note that we should not let other people change process mounts. 

That being said, the fact that TopoLVM does NOT use device-mapper even though lvm2 is written explicitly with this in mind is problematic. Everyones canonical expectation for lvm2 is that the device path /dev/vgname/lvname would be used for mounting and symlinking, not /dev/topolvm/xxx. That should probably be written into the docs. Similarly people do not expect udev rules to not work when the host lvm is used. In this regard TopoLVM is inconsistent because we use device management from the pod, but the lvm subsystem of the host.

**Comment by jakobmoellerdev** [comment] 2024-04-15 11:53
I think the issue is bigger than I originally thought. We can also not promote btrfs from experimental state because the device mapper mounts are not correctly unmounted: https://github.com/topolvm/topolvm/pull/879#issuecomment-2056628084 

I think this is all related due to btrfs using dmsetup in the kernel and causing remapping issues on mounts

**Comment by cupnes** [comment] 2024-04-16 09:51
@jakobmoellerdev 
Thank you for your explanation. I understood. However, the btrfs is experimental support in topolvm. So our team is not proactive about fixing. But if the PR is created, we will review it. So could you create the PR?
Note that another possible modification as an idea would be to "support the host `/dev/mapper` to be mounted on topolvm-node". (Either is fine.)

**Comment by jakobmoellerdev** [comment] 2024-04-16 09:53
I will have to think about a design proposal for this and potentially want to change the way we do device creation mounting. Would this be acceptable? If not it will be hard for me to get this running without a device mount or custom symlinking, both of which I would like to avoid

**Comment by cupnes** [comment] 2024-04-17 08:49
@jakobmoellerdev 
How about the following as relatively simple fixes? A design proposal is not necessary for this level of detail.

1. If `/proc/mounts` contains a path starting with `/dev/mapper`, check the major and minor numbers of the block special file to which the path points.
2. If the major and minor numbers match the major and minor numbers used to create the block special file, it can be judged to be mounted.

> I wonder why parted -l is changing the /proc/mounts here tbh. Do we have some info on that?

After running `parted -l`, the following message appeared in `dmesg`.

```
[91357.279111] BTRFS info: devid 1 device path /dev/mapper/ubuntu--vg-ubuntu--lv changed to /dev/dm-0 scanned by systemd-udevd (257020)
[91357.290952] BTRFS info: devid 1 device path /dev/dm-0 changed to /dev/mapper/ubuntu--vg-ubuntu--lv scanned by systemd-udevd (257020)
```

It appears that udev is changing the device path.

As for why this is a problem with btrfs, `/proc/mounts` uses `show_devname` if the filesystem implements it [1]. And btrfs implements it [2], so this seems to be the problem.
(I think they made it so we can dynamically change it because we can attach and detach devices, but I think it's causing the troubling behavior.)

[1] https://github.com/torvalds/linux/blob/96fca68c4fbf77a8185eb10f7557e23352732ea2/fs/proc_namespace.c#L109
[2] https://github.com/torvalds/linux/blob/96fca68c4fbf77a8185eb10f7557e23352732ea2/fs/btrfs/super.c#L2361

**Comment by jakobmoellerdev** [comment] 2024-04-17 09:08
Actually I think this may work. Let me see if that resolves our issue.

**Comment by toshipp** [comment] 2024-05-01 09:36
I doubt this is not fixed. we need #902, IMO

**Comment by toshipp** [comment] 2024-05-01 09:41
my bad. In #879, the device path is not used, so this should be fixed.

**Closed by toshipp** 2024-05-01 09:41 UTC
Labels: bug
