### ISSUE TITLE
nsenter: cannot open /proc/1/ns/cgroup: No such file or directory

### ISSUE THREAD

**Issue by attlee-wang** [topolvm/topolvm#363] opened 2021-09-08 07:28 UTC
**Describe the bug**
I used topolvm helm chart to deploy topolvm and found topolvm-lvmd Crash

![image](https://user-images.githubusercontent.com/57479557/132464628-26051486-a98e-40a6-9df5-80ef69166058.png)

View the topolvm-lvmd log as follows：

![image](https://user-images.githubusercontent.com/57479557/132464756-6625366a-36da-4605-9caf-ce50101c0dad.png)

After investigation, I found that there is no cgroup on my CVM

![image](https://user-images.githubusercontent.com/57479557/132465276-e4a4669c-18c5-47fa-ad17-ca68d45977a7.png)

**Environments**
- Version: v0.9.0
- OS: CentOS 7.6 3.10.0-1160.11.1.el7.x86_64

**To Reproduce**
1. Go to '...'  v1.16

**Expected behavior**

I want topolvm-lvmd to run correctly and read volume_group

**Additional context**

**Comment by toshipp** [comment] 2021-09-08 07:30
duplicate of #231

**Closed** 2021-09-10 01:19 UTC
Labels: bug
