### ISSUE TITLE
PV provisioning takes time after extending the Volume Group.

### ISSUE THREAD

**Issue by sp98** [topolvm/topolvm#399] opened 2021-11-24 05:01 UTC
**Describe the bug**
Tried to provision a PV with size greater than the Volume Group. PV didn't provision. Extended the Volume Group size to be greater than the requested PV.  PV is provisioned after more than 5 minutes.

**Environments**
- Version: master branch
- OS: rhel fedora

**To Reproduce**
1. Created a volume group with size 10 GB
```
sh-4.4# vgs
  VG    #PV #LV #SN Attr   VSize   VFree  
  myvg1   1   0   0 wz--n- <10.00g <10.00g
```
2. Deployed topolvm helm chart
```
NAME                                              READY   STATUS    RESTARTS   AGE
my-pod-1                                          1/1     Running   0          8m33s
topolvm-cert-manager-cainjector-97768874c-pt94l   1/1     Running   0          11m
topolvm-cert-manager-d746b79b-6kr8h               1/1     Running   0          11m
topolvm-cert-manager-webhook-786cf88f8-xl9cb      1/1     Running   0          11m
topolvm-controller-74d8b5f686-89h22               4/4     Running   0          11m
topolvm-controller-74d8b5f686-tp8r2               0/4     Pending   0          11m
topolvm-lvmd-0-74nc7                              1/1     Running   0          11m
topolvm-node-h9wp9                                3/3     Running   0          11m

```
3.  Applied `example/podpvc.yaml` with pvc size as `15Gi` (This size is greater than the Volume Group size of 10 Gi)
4. No PV provisioned. This is expected.
5. Extended the Volume Group to 20Gi
```
sh-4.4# vgextend myvg1 /dev/nvme3n1 
  Physical volume "/dev/nvme3n1" successfully created.
  Volume group "myvg1" successfully extended
sh-4.4# vgs
  VG    #PV #LV #SN Attr   VSize  VFree 
  myvg1   2   0   0 wz--n- 19.99g 19.99g
```

**Actual behavior**
- After Step 5, the pv gets provisioned after more than 5 minutes.
- Observe the PVC and PV age below:
```
# sapillai @ localhost in ~/go/src/github.com/topolvm/example on git:scc x [10:27:05] 
$ oc get pv               
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                             STORAGECLASS          REASON   AGE
pvc-e04786b8-e9fc-4b98-85a3-ea82090657c8   15Gi       RWO            Delete           Bound    openshift-topolvm/topolvm-pvc-1   topolvm-provisioner            10m

# sapillai @ localhost in ~/go/src/github.com/topolvm/example on git:scc x [10:27:09] 
$ oc get pvc 
NAME            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS          AGE
topolvm-pvc-1   Bound    pvc-e04786b8-e9fc-4b98-85a3-ea82090657c8   15Gi       RWO            topolvm-provisioner   18m

```
**Expected behavior**.
- PV provisioning should not take this much time. 
**Additional context**

**Comment by sp98** [comment] 2021-11-24 05:02
I'll test it more to confirm if this is happening every time.

**Comment by sp98** [comment] 2021-11-24 08:40
I can repro this behavior.  There is a significant delay after extending the vg. Observe the `Age` of the `topolvm-pvc-3` PVC and the corresponding PV in below sample: 

``` 
$ oc get pvc 
NAME            STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS            AGE
topolvm-pvc-2   Bound    pvc-1b8e8c08-bb14-4aca-bc9e-e443857bc36b   10Gi       RWO            topolvm-provisioner     32m
topolvm-pvc-3   Bound    pvc-8fd3bcde-56a1-4873-aa49-247354c46945   15Gi       RWO            topolvm-provisioner-2   24m
``` 
```$ oc get pv  
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                             STORAGECLASS            REASON   AGE
pvc-1b8e8c08-bb14-4aca-bc9e-e443857bc36b   10Gi       RWO            Delete           Bound    openshift-topolvm/topolvm-pvc-2   topolvm-provisioner              30m
pvc-8fd3bcde-56a1-4873-aa49-247354c46945   15Gi       RWO            Delete           Bound    openshift-topolvm/topolvm-pvc-3   topolvm-provisioner-2            14m
```

**Comment by cupnes** [comment] 2021-11-25 08:02
@sp98 
Could you give me the values.yaml file you used?
I will try to reproduce it.

**Comment by sp98** [comment] 2021-11-25 09:43
> @sp98 Could you give me the values.yaml file you used? I will try to reproduce it.

https://pastebin.com/SN991Sv5

**Comment by sp98** [comment] 2021-12-06 07:22
> @sp98 Could you give me the values.yaml file you used? I will try to reproduce it.

Hi @cupnes any update on this? Were you are to reproduce the behavior?

**Comment by cupnes** [comment] 2021-12-06 07:44
@sp98 I will be working on that this week. Please wait a little longer.

**Comment by cupnes** [comment] 2021-12-07 08:20
@sp98 I was able to reproduce this issue. This issue is because we put [a 10-minute wait](https://github.com/topolvm/topolvm/blob/9eea3dd64b3123a378c86c6bdeb485e9fdbba537/pkg/lvmd/cmd/root.go#L113) after checking the VG capacity. There is a risk in shortening this wait because LVM takes a lock. Therefore, this wait is fixed at 10 minutes. Do you want to make it adjustable?

**Comment by sp98** [comment] 2021-12-07 08:36
I'm not sure how the lvm lock mechanism works. I'll read more about this and get back to you.

**Comment by toshipp** [comment] 2022-01-21 01:14
We regard this as not a bug. I close this PR for now. Please reopen if you have any updates.

**Closed by toshipp** 2022-01-21 01:14 UTC
Labels: bug
