### ISSUE TITLE
After reboot topolvm-node container, online expand pvc doesn't work.

### ISSUE THREAD

**Issue by ottolane** [topolvm/topolvm#273] opened 2021-03-08 08:08 UTC
**Describe the bug**
Hi, I'm a new user of TopoLVM, my K8S version is 1.14, so I just follow the guide install the topolvm(0.4.0). it works fine at the begging, but I find a bug soon. 
After I reboot the node-xxxx POD, exactly the topolvm-node container, online expand pvc doesn't work, everything stuck.

POD stuck in such message:
 Warning  VolumeResizeFailed          2m36s (x19 over 25m)  kubelet, kpdbw03  VolumeFSResize.resizeFileSystem failed for volume "pvc-50a80e4d-7cba-11eb-935e-f4deaf2c811a" : MountVolume.resizeFileSystem failed : Expander.NodeExpanr: code = Internal desc = failed to detect filesystem of /dev/topolvm/50b12f57-7cba-11eb-9666-f4deaf2c80f0: open /dev/topolvm/50b12f57-7cba-11eb-9666-f4deaf2c80f0: no such file or directory

PVC stuck in thins：
FileSystemResizePending   True    Mon, 01 Jan 0001 00:00:00 +0000   Mon, 08 Mar 2021 15:57:41 +0800           Waiting for user to (re-)start a pod to finish file system resize of volume on node.
Event is:
  Normal     Resizing                  12s (x2 over 102m)   external-resizer topolvm.cybozu.com  External resizer is resizing volume pvc-50a80e4d-7cba-11eb-935e-f4deaf2c811a
  Normal     FileSystemResizeRequired  10s (x2 over 102m)   external-resizer topolvm.cybozu.com  Require file system resize of volume on node
Warning    ExternalExpanding         70s (x8 over 27m)     volume_expand                        Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
Mounted By:  kylin-statefulset-two-1

PV has expanded successfully，you can find that in the worker node，it's already expanded. but PVC can not.

there are 2 ways to solve this problem:
1.restart the app POD and it works find. but it's not ONLINE EXPAND.
2,umount filesystem in worker node, like this:
umount /var/lib/kubelet/pods/12f86edd-7fd5-11eb-8f73-f4deaf2c811a/volumes/kubernetes.io~csi/pvc-50a80e4d-7cba-11eb-935e-f4deaf2c811a/mount
THEN restart kubelet of this worker node, it works too. but it's not safe, it's dangerous.

WHY AFTER REBOOT THE TOPOLVM-NODE CONTAINER, ONLINE EXPAND DOES NOT WORK???

**Environments**
- Version: 0.4.0/0.6.0
- OS: Centos 8.1

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by ymmt2005** [comment] 2021-03-08 08:14
Duplicate of #143 and fixed in #144.

**Closed** 2021-03-09 01:16 UTC
Labels: bug
